server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 15

datasource:
  url: jdbc:postgresql://10.0.0.3:5432/demo
  username: demo
  password: DDsX18jKKK
  driver: org.postgresql.Driver
  ddl: none
  show_sql: true

logging:
  level: warn


