server:
  port: 8080

spring:
  jpa:
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 10
    url: jdbc:h2:~/demo;MODE=PostgreSQL
